styles
theRemix/Nineties-Namer pull request #7
Opened 2017-06-20 09:01 UTC by fobabett

2017-06-20 21:33 UTC, theRemix requested changes

2017-06-20 21:33 UTC, theRemix commented on ui/src/components/Hash.vue
> +      <input class="output" placeholder="result" value="key" disabled/>
this should display the value of `{{hashedName}}`

2017-06-20 21:34 UTC, theRemix commented on ui/src/components/Hash.vue
> +      <input class="output" placeholder="result" value="key" disabled/>
```html
      <input class="output" placeholder="result" v-model="hashedName" disabled/>
```
should do the trick

2017-06-20 21:38 UTC, theRemix requested changes
the "See example on Github" links should be outside of the dark gray code blocks

2017-06-20 21:38 UTC, theRemix commented on ui/src/components/ApiTabPanel/content/ContentCurl.vue
>    </div>
add "See example on Github" outside of the code block

2017-06-20 21:38 UTC, theRemix commented on ui/src/components/ApiTabPanel/content/ContentGo.vue
> +  <i>See: <a href="https://github.com/theRemix/Nineties-Namer/blob/master/routes/router.go">Example on Github</a></i>
move the "See example on Github" to outside of the code block

2017-06-20 21:38 UTC, theRemix commented on ui/src/components/ApiTabPanel/content/ContentJs.vue
>      <i>See: <a href="https://github.com/theRemix/Nineties-Namer/blob/master/ui/src/components/Random.vue">Random Example on Github</a></i>
move the "See example on Github" to outside of the code block

2017-06-20 21:38 UTC, theRemix commented on ui/src/components/ApiTabPanel/content/ContentJs.vue
>      <i>See: <a href="https://github.com/theRemix/Nineties-Namer/blob/master/ui/src/components/Hash.vue">Names Example on Github</a></i>
move the "See example on Github" to outside of the code block

2017-06-20 22:25 UTC, theRemix requested changes
add google fonts please
https://projects.invisionapp.com/share/43C7EQ1F8#/screens/239931045

2017-06-21 06:38 UTC, fobabett commented
made requested changes

2017-06-21 07:47 UTC, theRemix approved these changes

2017-06-21 07:48 UTC, merged